stages:
  - test
  - build
  - docs
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip

# -- test -------------------

.test: &test
  except:
    - /^debian.*$/
  image: python
  before_script:
    # install testing dependencies
    - python -m pip install setuptools_scm pytest pytest-cov
  script:
    # install package (using -e to get script coverage)
    - python -m pip install -e ${CI_PROJECT_DIR}
    # run tests
    - python -m pytest gpstime/test.py -v --cov gpstime --cov-report= --junitxml="junit.xml"
    #- python -m coverage run -a $(which gpstime)
    - python -m coverage report
  artifacts:
    reports:
      junit: junit.xml

test:3.7:
  <<: *test
  image: python:3.7

test:3.8:
  <<: *test
  image: python:3.8

test:3.9:
  <<: *test
  image: python:3.9

test:3.10:
  <<: *test
  image: python:3.10

# -- build ------------------

.build:debian: &build-debian
  only:
    - /^debian.*$/
  before_script:
    - apt-get update -yqq
    - apt-get install -yq
          dpkg-dev
          devscripts
          lintian
  script:
    - mkdir -pv dist
    # install build dependencies
    - mk-build-deps --tool "apt-get -y" --install --remove
    # build packages
    - dpkg-buildpackage -us -uc -b
    # lint packages
    - lintian ../gpstime_*.changes
    # move things into dist/
    - mv -v ../python3-gpstime_*.deb ../gpstime_*.{buildinfo,changes} dist/
  artifacts:
    paths:
      - dist/

build:debian:buster:
  <<: *build-debian
  image: debian:buster

build:debian:bullseye:
  <<: *build-debian
  image: debian:bullseye

# -- docs -------------------

docs:
  stage: docs
  except:
    - /^debian.*$/
  image: python
  before_script:
    # install docs requirements
    - python -m pip install sphinx sphinx_rtd_theme
    # install this package
    - python -m pip install .
  script:
    - _version=$(python setup.py --version)
    - mkdir -v docs
    - cd docs
    # generate docs skeleton
    - python -m sphinx.ext.apidoc
          --module-first
          --separate
          --full
          --ext-autodoc
          --ext-intersphinx
          --doc-project "gpstime"
          --doc-author "California Institute of Technology"
          --doc-version "${_version}"
          --output-dir .
          ../gpstime
    # use sphinx_rtd_theme
    - sed -i 's/alabaster/sphinx_rtd_theme/g' conf.py
    # run sphinx to generate docs
    - python -m sphinx -b html . html
  artifacts:
    paths:
      - docs/html

pages:
  stage: deploy
  except:
    - /^debian.*$/
  dependencies:
    - docs
  only:
    - tags
  script:
    - mv docs/html public
  artifacts:
    paths:
      - public
